### ISSUE TITLE
Join/Leave spike buttons on mobile

### ISSUE THREAD

**Issue by Jeff-Duke** [Jeff-Duke/turing-fridays#134]
On mobile, at least on iPhone, the text on the join/leave buttons are overflowing the button.  
![img_1244](https://cloud.githubusercontent.com/assets/17116730/22023450/67e27d04-dc83-11e6-8d01-632ebe46ab06.PNG)

**Comment by swanie21** [comment]
I can fix this!

**Comment by Jeff-Duke** [comment]
This was resolved in PR #132
