### ISSUE TITLE
Need a route from Admin spike approval page to list of currently displayed/approved spikes

### ISSUE THREAD

**Issue by kccrs** [Jeff-Duke/turing-fridays#17]

**Comment by kerrd89** [comment]
closing this since it is a duplicate of 24

**Comment by kccrs** [comment]
This is not a duplicate of 24 - reopening.  This is not a style issue, it's a functionality issue.

**Comment by Jeff-Duke** [comment]
I think @kerrd89 is working on a filtering function for the admin page to let an admin see approved, pending, all etc that should take care of this.
