### ISSUE TITLE
Admins security

### ISSUE THREAD

**Issue by Jeff-Duke** [Jeff-Duke/turing-fridays#52]
Currently we're pulling all the admins down from firebase into a local array as an interim step.  We should leverage Firebase's permissions so that record updates/adds/deletes are checked against the DB permissions and are only allowed for the folks with proper permissions as set by a project owner.  This will add a layer of security against someone flagging themselves as an admin on the client side and altering/deleting scheduled spikes.

**Comment by Peter-Springer** [comment]
Firebase rules have been updated so only specific users can grant someone admin status. Will look into hiding fields for users not on this list.

**Comment by Peter-Springer** [comment]
this issue is resolved with PR #74
