### ISSUE TITLE
Set UI to only display current spikes

### ISSUE THREAD

**Issue by Jeff-Duke** [Jeff-Duke/turing-fridays#53]
As a user or an Admin I should only see approved spikes that are upcoming, preferably only spikes for the nearest Friday.  As an MVP step we can probably just check the spikes as they're taken off the server to determine if the spikeDate > Date.now(), otherwise don't display them.  

Maybe we could improve on this with a function or process that cleans out old spikes automatically?

**Comment by Jeff-Duke** [comment]
Can this be closed with David's PR?

**Comment by kccrs** [comment]
Yup
