### ISSUE TITLE
Admin Page -- Make pending vs approved cards more distinguished

### ISSUE THREAD

**Issue by Jeff-Duke** [Jeff-Duke/turing-fridays#70]
As an admin it'd be nice to have a more prominent visual representation of what is pending vs what is approved.  Some thoughts:
* Put different classes on the cards based on their approval status.
* Create separate sections on the page so that pending vs approved are in separate places.

**Comment by Peter-Springer** [comment]
I think the second bullet point is covered by our filter functionality.

**Comment by kccrs** [comment]
I think this can be closed as there is definitely some almondy business happening on approval.
